spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  h2:
    console:
      enabled: true    # Enable the H2 console for easy access
      path: /h2-console # Customize the console's path (optional)
